### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drok** [pjhades/bash-snake#6]
Hi @pjhades ,

What a brilliant piece of work! Thank you. I wrapped your script in a Makefile at https://github.com/drok/sneaky-snake-Makefiles to demonstrate two less-well-known facts about makefiles.

I hope you don't mind. Would it be possible for you to add a license statement for peace of mind?

Thanks!

**Comment by pjhades** [comment]
Hi, thanks for your interest in the code! I have added an MIT license and hopefully it could make your life easier. Cheers!
